# Generated by Django 4.0.4 on 2022-05-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='user',
            new_name='auth',
        ),
    ]
