# Generated by Django 4.0.4 on 2022-05-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_user_blogmodel_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='auth',
            new_name='bloger',
        ),
    ]
