# Generated by Django 4.0.4 on 2022-05-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blogmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='bloger',
            new_name='user',
        ),
    ]
