# Generated by Django 4.0.4 on 2022-05-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_bloger_blogmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_at',
        ),
    ]
