# Generated by Django 4.0.4 on 2022-05-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_category_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
