# Generated by Django 4.0.4 on 2022-05-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_title_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name_plural': 'All Blogs'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile Verification'},
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='sub_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
