# Generated by Django 4.0.4 on 2022-06-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
                ('feed', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.blogmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
